### ISSUE TITLE
`-DCMAKE_BUILD_TYPE=Debug` fails to build

### ISSUE THREAD

**Issue by trofi** [vcmi/vcmi#2047]
**Describe the bug**

Attempt to build `vcmi` with asserts enabled fails:

```
$ cmake .. -DCMAKE_BUILD_TYPE=Debug
$ make
...
[  0%] Building CXX object lib/CMakeFiles/vcmi.dir/NetPacksLib.cpp.o
In file included from /<<NIX>>/gcc-14.0.0/include/c++/14.0.0/cassert:44,
                 from include/boost/mp11/detail/mp_with_index.hpp:15,
                 from include/boost/mp11/algorithm.hpp:19,
                 from include/boost/mp11/bind.hpp:11,
                 from include/boost/parameter/aux_/is_placeholder.hpp:46,
                 from include/boost/parameter/value_type.hpp:101,
                 from include/boost/parameter/aux_/name.hpp:31,
                 from include/boost/parameter/name.hpp:10,
                 from include/boost/heap/policies.hpp:13,
                 from include/boost/heap/detail/stable_heap.hpp:21,
                 from include/boost/heap/fibonacci_heap.hpp:21,
                 from vcmi/lib/CPathfinder.h:17,
                 from vcmi/lib/CGameState.h:23,
                 from vcmi/lib/NetPacksLib.cpp:23:
vcmi/lib/NetPacksLib.cpp: In member function 'void AssembledArtifact::applyGs(CGameState*)':
vcmi/lib/NetPacksLib.cpp:1918:50: error: 'const class CArtifactInstance' has no member named 'assemblyPossibilities'
 1918 |         assert(vstd::contains_if(transformedArt->assemblyPossibilities(artSet, combineEquipped), [=](const CArtifact * art)->bool
```

**Version**
 - OS: `x86_64-linux`
 - Version: `develop` branch

**Comment by Alexander-Wilms** [comment]
I think I found the issue:
```
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::create_directories: Read-only file system [system:30]: "./Saves", "./Saves"

Program received signal SIGABRT, Aborted.
0x00007ffff6d1049b in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff6d1049b in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6cf9857 in abort () from /usr/lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff70a98b9 in __gnu_cxx::__verbose_terminate_handler() [clone .cold] () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff70b55aa in __cxxabiv1::__terminate(void (*)()) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff70b5615 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff70b58a1 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7f89cea in ?? () from /app/lib/libboost_filesystem.so.1.82.0
#7  0x00007ffff7cb5dd4 in IVCMIDirs::init() () from /app/lib/libvcmi.so
#8  0x00007ffff7381073 in __pthread_once_slow () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00007ffff7cb5c63 in VCMIDirs::get() () from /app/lib/libvcmi.so
#10 0x00005555555b397c in ?? ()
#11 0x00007ffff6cfab80 in __libc_start_main () from /usr/lib/x86_64-linux-gnu/libc.so.6
#12 0x00005555555b507e in ?? ()
(gdb) bt full
#0  0x00007ffff6d1049b in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007ffff6cf9857 in abort () from /usr/lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#2  0x00007ffff70a98b9 in __gnu_cxx::__verbose_terminate_handler() [clone .cold] () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00007ffff70b55aa in __cxxabiv1::__terminate(void (*)()) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x00007ffff70b5615 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#5  0x00007ffff70b58a1 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x00007ffff7f89cea in ?? () from /app/lib/libboost_filesystem.so.1.82.0
No symbol table info available.
#7  0x00007ffff7cb5dd4 in IVCMIDirs::init() () from /app/lib/libvcmi.so
No symbol table info available.
#8  0x00007ffff7381073 in __pthread_once_slow () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#9  0x00007ffff7cb5c63 in VCMIDirs::get() () from /app/lib/libvcmi.so
No symbol table info available.
#10 0x00005555555b397c in ?? ()
No symbol table info available.
#11 0x00007ffff6cfab80 in __libc_start_main () from /usr/lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#12 0x00005555555b507e in ?? ()
No symbol table info available.
```

<details>
<summary>vcmiserver</summary>

```
flatpak enter eu.vcmi.VCMI sh
sh-5.1$ gdb vcmiserver
gdb: warning: Couldn't determine a path for the index cache directory.
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from vcmiserver...
(No debugging symbols found in vcmiserver)
(gdb) run
Starting program: /app/bin/vcmiserver 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::create_directories: Read-only file system [system:30]: "./Saves", "./Saves"

Program received signal SIGABRT, Aborted.
0x00007ffff6d1049b in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff6d1049b in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6cf9857 in abort () from /usr/lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff70a98b9 in __gnu_cxx::__verbose_terminate_handler() [clone .cold] () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff70b55aa in __cxxabiv1::__terminate(void (*)()) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff70b5615 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff70b58a1 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7f89cea in ?? () from /app/lib/libboost_filesystem.so.1.82.0
#7  0x00007ffff7cb5dd4 in IVCMIDirs::init() () from /app/lib/libvcmi.so
#8  0x00007ffff7381073 in __pthread_once_slow () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00007ffff7cb5c63 in VCMIDirs::get() () from /app/lib/libvcmi.so
#10 0x00005555555b397c in ?? ()
#11 0x00007ffff6cfab80 in __libc_start_main () from /usr/lib/x86_64-linux-gnu/libc.so.6
#12 0x00005555555b507e in ?? ()
(gdb) bt full
#0  0x00007ffff6d1049b in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007ffff6cf9857 in abort () from /usr/lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#2  0x00007ffff70a98b9 in __gnu_cxx::__verbose_terminate_handler() [clone .cold] () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00007ffff70b55aa in __cxxabiv1::__terminate(void (*)()) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x00007ffff70b5615 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#5  0x00007ffff70b58a1 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x00007ffff7f89cea in ?? () from /app/lib/libboost_filesystem.so.1.82.0
No symbol table info available.
#7  0x00007ffff7cb5dd4 in IVCMIDirs::init() () from /app/lib/libvcmi.so
No symbol table info available.
#8  0x00007ffff7381073 in __pthread_once_slow () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#9  0x00007ffff7cb5c63 in VCMIDirs::get() () from /app/lib/libvcmi.so
No symbol table info available.
#10 0x00005555555b397c in ?? ()
No symbol table info available.
#11 0x00007ffff6cfab80 in __libc_start_main () from /usr/lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#12 0x00005555555b507e in ?? ()
No symbol table info available.
(gdb) thread apply all bt full

Thread 1 (Thread 0x7ffff7235740 (LWP 60) "vcmiserver"):
#0  0x00007ffff6d1049b in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007ffff6cf9857 in abort () from /usr/lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#2  0x00007ffff70a98b9 in __gnu_cxx::__verbose_terminate_handler() [clone .cold] () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00007ffff70b55aa in __cxxabiv1::__terminate(void (*)()) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x00007ffff70b5615 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#5  0x00007ffff70b58a1 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x00007ffff7f89cea in ?? () from /app/lib/libboost_filesystem.so.1.82.0
No symbol table info available.
#7  0x00007ffff7cb5dd4 in IVCMIDirs::init() () from /app/lib/libvcmi.so
No symbol table info available.
#8  0x00007ffff7381073 in __pthread_once_slow () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#9  0x00007ffff7cb5c63 in VCMIDirs::get() () from /app/lib/libvcmi.so
No symbol table info available.
#10 0x00005555555b397c in ?? ()
No symbol table info available.
#11 0x00007ffff6cfab80 in __libc_start_main () from /usr/lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#12 0x00005555555b507e in ?? ()
No symbol table info available.
(gdb) 
```
</details>
<details>
<summary>vcmiclient</summary>

```
flatpak run --devel --command=sh eu.vcmi.VCMI//test
[📦 eu.vcmi.VCMI ~]$ vcmiclient
Starting... 
VCMI 1.3.0 (client)
Creating console and configuring logger: 0 ms
The log file will be saved to "/home/alexander/.var/app/eu.vcmi.VCMI/cache/vcmi/VCMI_Client_log.txt"
        Initialization: 5 ms
        Data loading: 70 ms
        Mod handler: 1 ms
        Mod filesystems: 14 ms
Initialized logging system based on settings successfully.
[log level] ai => not set
[log level] animation => not set
[log level] bonus => not set
[log level] global => trace
[log level] mod => not set
[log level] network => not set
Loading settings: 97 ms
Found 3 render drivers
        opengl (active)
        opengles2
        software
Check display mode: requested 800 x 600; available up to 2560 x 1440 
Set logical rendering resolution to 800x600
Created renderer opengl
        Initializing screen: 135 ms
        Initializing video: 0 ms
Initializing screen and sound handling: 2 ms
                 Game Settings handler: 0 ms
                 General text handler: 9 ms
                 Bonus type handler: 5 ms
                 Road handler: 0 ms
                 River handler: 0 ms
                 Terrain handler: 0 ms
                 Hero handler: 0 ms
                 Artifact handler: 0 ms
                 Creature handler: 0 ms
                 Town handler: 0 ms
                 Object handler: 0 ms
                 Object types information handler: 0 ms
                 Spell handler: 0 ms
                 Skill handler: 0 ms
                 Terrain view pattern handler: 1 ms
                 Template handler: 0 ms
                 Battlefields handler: 0 ms
                 Obstacles handler: 0 ms
        Initializing handlers: 17 ms
        Initializing content handler: 0 ms
Invalid return value 0 for stream protocol
Error: video VIDEO/AZVS was not found
                [49278cbc]Original game files
                [f6cd5e31]VCMI essential files
                [a85a7296]VCMI extras
                [79eb77d0]Arrow Tower Icons
                [68588ff9]Battlefield actions
                [c4d647ff]Andruids Bonus Icons
                [2398231e]Extended RMG options
                [5e17bbe6]Extra resolutions
                [cf3c5dd9]VCMI Quick Exchange
                [af85aeb5]Bonus Icons
                [08458f5a]Spell Immunity Bonus Icons
        Parsing mod data: 122 ms
                [SKIP] Original game files
                [SKIP] VCMI essential files
                [SKIP] VCMI extras
                [SKIP] Arrow Tower Icons
                [SKIP] Battlefield actions
                [SKIP] Andruids Bonus Icons
                [SKIP] Extended RMG options
                [SKIP] Extra resolutions
                [SKIP] VCMI Quick Exchange
                [SKIP] Bonus Icons
                [SKIP] Spell Immunity Bonus Icons
        Loading mod data: 65 ms
        Resolving identifiers: 8 ms
        Handlers post-load finalization: 1 ms 
        All game content loaded in 197 ms
Initializing VCMI_Lib: 215 ms
Screen handler: 4 ms
Message handler: 0 ms
Initialization of VCMI (together): 456 ms
Found endpoints:
        0:127.0.0.1:3030
Trying connection to 127.0.0.1:3030(0)
Established connection with VCMI 1.3.0 (server). UUID: 526e366e-fb2b-45b5-846b-83c58970a7d9
Port is busy, check if another instance of vcmiserver is working
Network error receiving a pack. Connection Connection with VCMI 1.3.0 (server) (ID: 0 UUID: 526e366e-fb2b-45b5-846b-83c58970a7d9) dies. What happened: read_some: End of file [asio.misc:2]
Found endpoints:
        0:127.0.0.1:3030
Trying connection to 127.0.0.1:3030(0)
Server command line: /app/bin/vcmiserver --port=3030 --run-by-client --uuid=91d1d56b-5af6-49ba-b42b-e0321d148102 --enable-shm > "/home/alexander/.var/app/eu.vcmi.VCMI/cache/vcmi/server_log.txt"
Establishing connection...
Found endpoints:
        0:127.0.0.1:3030
Trying connection to 127.0.0.1:3030(0)
Established connection with VCMI 1.3.0 (server). UUID: 9766a5f7-f56f-44b7-bdd4-9d9bda77ffff
Lost connection to server, ending listening thread!
read_some: End of file [asio.misc:2]
Error: server failed to close correctly or crashed!
Check /home/alexander/.var/app/eu.vcmi.VCMI/cache/vcmi/server_log.txt for more info
```

**Comment by IvanSavenko** [comment]
Already fixed
