### ISSUE TITLE
Crash on visiting town with bonusing building

### ISSUE THREAD

**Issue by nullkiller** [vcmi/vcmi#2133]
**Describe the bug**
A crash on visiting town with bonusing building.

**To Reproduce**
1. Capture a town or maybe revisit own town Castle with Stables in order to get Stables movement bonus
2. Observe server crash

**Expected behavior**
Movement bonus should be granted by Stables. Message dialog should appear.

**Actual behavior**
A server crash. Looks like COPWBonus::town is nullptr

`#0  CGTownInstance::hasBuilt (this=0x0, buildingID=...) at /home/rilian/Projects/vcmi/lib/mapObjects/CGTownInstance.cpp:942
#1  0x00007ffff77d3d26 in COPWBonus::onHeroVisit (this=0x7fffe4acce60, h=0x7fffe4785230) at /home/rilian/Projects/vcmi/lib/mapObjects/CGTownBuilding.cpp:137
#2  0x00005555555c9cfc in CGameHandler::visitCastleObjects (this=<optimized out>, t=<optimized out>, h=0x7fffe4785230) at /home/rilian/Projects/vcmi/server/CGameHandler.cpp:2614
#3  0x00005555555c8ddb in CGameHandler::heroVisitCastle (this=0x7fffe400c960, obj=0x7fffe4adb470, hero=0x7fffe4785230) at /home/rilian/Projects/vcmi/server/CGameHandler.cpp:2606
#4  0x00007ffff77d7f61 in CGTownInstance::onHeroVisit (this=0x7fffe4adb470, h=0x7fffe4785230) at /home/rilian/Projects/vcmi/lib/mapObjects/CGTownInstance.cpp:289
#5  0x00005555555eccfc in CGameHandler::objectVisited(CGObjectInstance const*, CGHeroInstance const*)::$_21::operator()(events::ObjectVisitStarted&) const (this=0x7fffe45cc1e0, event=...)
    at /home/rilian/Projects/vcmi/server/CGameHandler.cpp:5576
#6  std::__invoke_impl<void, CGameHandler::objectVisited(CGObjectInstance const*, CGHeroInstance const*)::$_21&, events::ObjectVisitStarted&>(std::__invoke_other, CGameHandler::objectVisited(CGObjectInstance const*, CGHeroInstance const*)::$_21&, events::ObjectVisitStarted&) (__f=..., __args=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/invoke.h:61
#7  std::__invoke_r<void, CGameHandler::objectVisited(CGObjectInstance const*, CGHeroInstance const*)::$_21&, events::ObjectVisitStarted&>(CGameHandler::objectVisited(CGObjectInstance const*, CGHeroInstance const*)::$_21&, events::ObjectVisitStarted&) (__fn=..., __args=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/invoke.h:111
#8  std::_Function_handler<void (events::ObjectVisitStarted&), CGameHandler::objectVisited(CGObjectInstance const*, CGHeroInstance const*)::$_21>::_M_invoke(std::_Any_data const&, events::ObjectVisitStarted&) (__functor=..., 
    __args=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/std_function.h:290
#9  0x00007ffff77887b6 in std::function<void (events::ObjectVisitStarted&)>::operator()(events::ObjectVisitStarted&) const (this=0x7ffff3dfd470, __args=...)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/std_function.h:591
#10 events::SubscriptionRegistry<events::ObjectVisitStarted>::executeEvent(events::EventBus const*, events::ObjectVisitStarted&, std::function<void (events::ObjectVisitStarted&)> const&) (this=0x7fffe46a6a00, bus=0x7fffe400bed0, 
    event=..., execHandler=...) at /home/rilian/Projects/vcmi/lib/../include/vcmi/events/SubscriptionRegistry.h:71
#11 0x00007ffff778820f in events::ObjectVisitStarted::defaultExecute(events::EventBus const*, std::function<void (events::ObjectVisitStarted&)> const&, PlayerColor const&, ObjectInstanceID const&, ObjectInstanceID const&) (
    bus=0x7fffe400bed0, execHandler=..., player=..., heroId=..., objId=...) at /home/rilian/Projects/vcmi/lib/events/ObjectVisitStarted.cpp:32
#12 0x00005555555e5e33 in CGameHandler::objectVisited (this=this@entry=0x7fffe400c960, obj=<optimized out>, h=<optimized out>) at /home/rilian/Projects/vcmi/server/CGameHandler.cpp:5579
#13 0x00005555555c6cf6 in CGameHandler::visitObjectOnTile (this=0x7fffe400c960, t=..., h=0x7fffe4785230) at /home/rilian/Projects/vcmi/server/CGameHandler.cpp:6068
#14 CGameHandler::moveHero(ObjectInstanceID, int3, unsigned char, bool, PlayerColor)::$_9::operator()(TryMoveHero::EResult, CGameHandler::EGuardLook, CGameHandler::EVisitDest, CGameHandler::ELEaveTile) const (
    this=this@entry=0x7ffff3dfd918, result=result@entry=TryMoveHero::SUCCESS, lookForGuards=CGameHandler::CHECK_FOR_GUARDS, visitDest=CGameHandler::VISIT_DEST, leavingTile=leavingTile@entry=CGameHandler::LEAVING_TILE)
    at /home/rilian/Projects/vcmi/server/CGameHandler.cpp:2354
#15 0x00005555555c634a in CGameHandler::moveHero (this=0x7fffe400c960, hid=..., dst=..., teleporting=0 '\000', transit=false, asker=...) at /home/rilian/Projects/vcmi/server/CGameHandler.cpp:2441
#16 0x00005555556d0395 in ApplyGhNetPackVisitor::visitMoveHero (this=0x7ffff3dfdb08, pack=...) at /home/rilian/Projects/vcmi/server/NetPacksServer.cpp:63
#17 0x000055555561048f in CApplyOnGH<MoveHero>::applyOnGH (this=<optimized out>, gh=<optimized out>, gs=0x7fffe4785230, pack=0x0) at /home/rilian/Projects/vcmi/server/CGameHandler.cpp:96
#18 0x00005555555bb8f4 in CGameHandler::handleReceivedPack (this=0x7fffe400c960, pack=0x0) at /home/rilian/Projects/vcmi/server/CGameHandler.cpp:1264
#19 0x0000555555693d05 in CVCMIServerPackVisitor::visitForServer (this=<optimized out>, serverPack=...) at /home/rilian/Projects/vcmi/server/CVCMIServer.cpp:396
#20 0x00007ffff7ce7d90 in CPack::visit (this=0x0, visitor=...) at /home/rilian/Projects/vcmi/lib/NetPacksLib.cpp:39
#21 0x000055555568542b in CVCMIServer::threadHandleClient (this=0x7fffffffd938, c=std::shared_ptr<CConnection> (use count 11, weak count 1) = {...}) at /home/rilian/Projects/vcmi/server/CVCMIServer.cpp:439
#22 0x00005555556c496f in boost::_mfi::mf1<void, CVCMIServer, std::shared_ptr<CConnection> >::operator() (this=<optimized out>, p=<optimized out>, a1=std::shared_ptr<CConnection> (use count 11, weak count 1) = {...})
    at /usr/include/boost/bind/mem_fn_template.hpp:165
#23 0x00005555556c4872 in boost::_bi::list2<boost::_bi::value<CVCMIServer*>, boost::_bi::value<std::shared_ptr<CConnection> > >::operator()<boost::_mfi::mf1<void, CVCMIServer, std::shared_ptr<CConnection> >, boost::_bi::list0> (
    this=<optimized out>, f=..., a=...) at /usr/include/boost/bind/bind.hpp:298
#24 0x00005555556c47fc in boost::_bi::bind_t<void, boost::_mfi::mf1<void, CVCMIServer, std::shared_ptr<CConnection> >, boost::_bi::list2<boost::_bi::value<CVCMIServer*>, boost::_bi::value<std::shared_ptr<CConnection> > > >::operator()
    (this=0x7fffe4acce78) at /usr/include/boost/bind/bind.hpp:1273
#25 boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf1<void, CVCMIServer, std::shared_ptr<CConnection> >, boost::_bi::list2<boost::_bi::value<CVCMIServer*>, boost::_bi::value<std::shared_ptr<CConnection> > > > >::run
    (this=<optimized out>) at /usr/include/boost/thread/detail/thread.hpp:120
#26 0x00007ffff730ccbb in ?? () from /usr/lib/libboost_thread.so.1.81.0
#27 0x00007ffff6db6bb5 in ?? () from /usr/lib/libc.so.6
#28 0x00007ffff6e38d90 in ?? () from /usr/lib/libc.so.6`

**Did it work earlier?**
Yes.

**Version**
 - OS: Windows
 - Version: 1.3 latest develop

**Comment by nullkiller** [comment]
[push-4-1.zip](https://github.com/vcmi/vcmi/files/11412442/push-4-1.zip)
A test map.
Pass 2 turns as green (Rampart)
Make save
Load save
Cast vcminahar
Capture some Castle

**Comment by nullkiller** [comment]
Looks like clone of https://github.com/vcmi/vcmi/issues/2110
