### ISSUE TITLE
Crash when I press "Start game"

### ISSUE THREAD

**Issue by beloglazov** [vcmi/vcmi#4571]
I have the VCMI Android app installed on Chrome OS. The app starts up and finds the game files. However, when I press "Start game" it crashes with the following logcat:

```
09-07 18:37:01.359  4798  4798 V SDL     : Device: nissa_cheets
09-07 18:37:01.359  4798  4798 V SDL     : Model: nissa
09-07 18:37:01.359  4798  4798 V SDL     : onCreate()
09-07 18:37:01.363  4798  4798 W System.err: dlopen failed: library "libvcmiclient_x86_64.so" not found
09-07 18:37:01.377  4798  4798 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10062; state: ENABLED
09-07 18:37:01.387   425  2160 D CoreBackPreview: Window{50fb4d7 u0 is.xyz.vcmi/eu.vcmi.vcmi.VcmiSDLActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@82498ad, mPriority=0}
09-07 18:37:01.390  4798  4798 D AndroidRuntime: Shutting down VM
09-07 18:37:01.391  4798  4798 E AndroidRuntime: FATAL EXCEPTION: SDLActivity
09-07 18:37:01.391  4798  4798 E AndroidRuntime: Process: is.xyz.vcmi, PID: 4798
09-07 18:37:01.391  4798  4798 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{is.xyz.vcmi/eu.vcmi.vcmi.VcmiSDLActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3672)
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3809)
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7950)
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
09-07 18:37:01.391  4798  4798 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at eu.vcmi.vcmi.VcmiSDLActivity.onCreate(VcmiSDLActivity.java:105)
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8290)
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8269)
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1402)
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3653)
09-07 18:37:01.391  4798  4798 E AndroidRuntime:        ... 12 more
```

It looks like it happens because `SDLActivity` fails to find the `libvcmiclient_x86_64.so` library. I assume it happens here https://github.com/vcmi/vcmi/blob/617952136428c62b99b1d393a1178f7ca59572d1/android/vcmi-app/src/main/java/org/libsdl/app/SDLActivity.java#L336 

The Chromebook I'm running this on is x86_64, is it possible that this library is not included in the Android app?

**Version**
 - OS: Chrome OS (Android 13)
 - Version: VCMI 1.5.7

**Comment by Laserlicht** [comment]
Since we have already had the problem several times: @IvanSavenko Should we add also android x86_64 to the dependencies and compile it also for x86_64? Shouldn't be that hard I think?

**Comment by Laserlicht** [comment]
@beloglazov The only way currently on x86_64 chromebook is to enable linux subsystem and install e.g. flatpak version of VCMI.

**Comment by kambala-decapitator** [comment]
> Since we have already had the problem several times: @IvanSavenko Should we add also android x86_64 to the dependencies and compile it also for x86_64? Shouldn't be that hard I think?

We could, why not. As another advantage it would allow running vcmi on AVD.

**Comment by kutovy** [comment]
Any updates on this one? 
Having same issue on my Chromebook

**Comment by IvanSavenko** [comment]
At the moment best option for Chromebooks is to:
1. install flatpak: https://flatpak.org/setup/Chrome%20OS
2. use flatpak to install vcmi: https://flathub.org/apps/eu.vcmi.VCMI

**Comment by kambala-decapitator** [comment]
Or build everything from source yourself

**Comment by kambala-decapitator** [comment]
@beloglazov @kutovy please test `android-64-intel` artifact from https://github.com/vcmi/vcmi/actions/runs/17037076748
