### ISSUE TITLE
Map filename with repeated extension will cause crash due to "No such file or directory"

### ISSUE THREAD

**Issue by nickhuang99** [vcmi/vcmi#4833]
**Describe the bug**
Placing a map file with such name pattern(i.e. "**someName.h3m.h3m**") will cause crash due to **No such file or directory**

The root cause is class "**ResourcePath**" ctor initialize "originalName" by calling "readName" during initialization which chop off extension. If later, a "resource name" is given "**ResourcePath**" again, the "**originalName**" will continue to be chopped off "extension". Then, "**originalName**" won't match "original" file path. 

In sense of variable name of "**originalName**", do we really need to chop off "extension"?  The other variable "**name**" which represent "resource" name without directory and extension already fulfill this purpose. And we should leave "**originalName**" as it is without chopping off extension. If we still want to remove directory part for uniformity, that should be ok.

**Game logs**
For a single map file name 
<code>
$ ll Maps/
total 28
drwxrwxr-x  2 nick nick  4096 Oct 28 05:43 ./
drwxrwxr-x 11 nick nick  4096 Oct 28 06:18 ../
-rw-rw-r--  1 nick nick 18120 Oct 27 05:47 M_xandallies.h3m.h3m
</code>

This is relevant backtrace of crash in gdb:

<code>
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140736093750848) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140736093750848) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140736093750848, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff4442476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff44287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff48d836f in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff6de28c5 in std::_Optional_base_impl<boost::filesystem::path, std::_Optional_base<boost::filesystem::path, false, false> >::_M_get() (this=0x7fffacdfe360)
    at /usr/include/c++/12/optional:477
#7  0x00007ffff72ed920 in std::optional<boost::filesystem::path>::operator*() && (this=0x7fffacdfe360) at /usr/include/c++/12/optional:978
#8  0x00007ffff72ebcc2 in CMapInfo::mapInit(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    (this=0x7fff2c2a47e0, fname="MAPS/M_xandallies.h3m") at /home/nick/workspace/vcmi/lib/mapping/CMapInfo.cpp:49
#9  0x0000555555c027d6 in SelectionTab::parseMaps(std::unordered_set<ResourcePath, std::hash<ResourcePath>, std::equal_to<ResourcePath>, std::allocator<ResourcePath> > const&) (this=0x7fff2c0e6f50, files=std::unordered_set with 1 element = {...}) at /home/nick/workspace/vcmi/client/lobby/SelectionTab.cpp:811
#10 0x0000555555bfd973 in SelectionTab::toggleMode() (this=0x7fff2c0e6f50) at /home/nick/workspace/vcmi/client/lobby/SelectionTab.cpp:261
...
</code>

**parseMaps** is given a parameter of **ResourcePath** with **originalName** as **M_xandallies.h3m.h3m** of which extension has been chopped off.

<code>
#10 0x0000555555bfd973 in SelectionTab::toggleMode (this=0x7fff2c0e6f50) at /home/nick/workspace/vcmi/client/lobby/SelectionTab.cpp:261
261					parseMaps(files);
(gdb) p files
$2 = std::unordered_set with 1 element = {[0] = {type = EResType::MAP, name = "MAPS/M_XANDALLIES.H3M", originalName = "MAPS/M_xandallies.h3m"}}
</code>

Later when **CMapInfo::mapInit** using this "**originalName**" by calling **ResourcePath** ctor again, then this time **originalName** is chopped off extension again, becoming **MAPS/M_xandallies**. (See below)

<code>
(gdb) frame 8
#8  0x00007ffff72ebcc2 in CMapInfo::mapInit (this=0x7fff2c2a47e0, fname="MAPS/M_xandallies.h3m") at /home/nick/workspace/vcmi/lib/mapping/CMapInfo.cpp:49
49		fullFileURI = boost::filesystem::canonical(*CResourceHandler::get()->getResourceName(resource)).string();
(gdb) l
44	{
45		fileURI = fname;
46		CMapService mapService;
47		ResourcePath resource = ResourcePath(fname, EResType::MAP);
48		originalFileURI = resource.getOriginalName();
49		fullFileURI = boost::filesystem::canonical(*CResourceHandler::get()->getResourceName(resource)).string();
50		mapHeader = mapService.loadMapHeader(resource);
51		countPlayers();
52	}
53	
(gdb) p resource
$3 = {type = EResType::MAP, name = "MAPS/M_XANDALLIES", originalName = "MAPS/M_xandallies"}
</code>

**To Reproduce**

1. Make a copy of original Maps folder under _~/.local/share/vcmi/Maps_ and delete all map files.
2. Copy any single map file under above folder and rename it by adding an extra extension like **.h3m**. For example, map file name as **M_xandallies.h3m.h3m**.
3. run vcmiclient and start new game of single scenario
4. See crash

**Expected behavior**
It is difficult to prevent repeatedly using of **ResourcePath** as parameter. So, better maintain **originalName** as it is would be much easier.

**Actual behavior**

**Did it work earlier?**
If this something which worked well some time ago, please let us know about version where it works or at date when it worked.

**Screenshots**

**Version**
 - OS: [e.g. Windows, macOS Intel, macOS ARM, Android, Linux, iOS]
 - Version: [VCMI version]

**Additional context**

**Comment by Whalios** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
